TENSORBOARD_DIR: "../data/tb/gala_kinematic_ddppo"
WRITER_TYPE: "tb"
CHECKPOINT_FOLDER: "../data/ckpt/gala_kinematic_ddppo"
EVAL_CKPT_PATH_DIR: "../data/ckpt/gala_kinematic_ddppo"
VIDEO_DIR: "../videos"
VIDEO_OPTION: ["disk"]
REWARD_SCALE: 1.0 # 0.01
NUM_CHECKPOINTS: 2
BATCHED_ENV: True
OVERLAP_PHYSICS: True
SAVE_VIDEOS_INTERVAL: 500
LOG_INTERVAL: 10
NUM_UPDATES: 31
TOTAL_NUM_STEPS: -1.0
NUM_ENVIRONMENTS: 4
MAX_EPISODE_LENGTH: 500
STAGGER: True
ENABLE_ROBOT_COLLISION: True
ENABLE_HELD_OBJECT_COLLISION: True
PICK_REWARD : 5.0
TASK_IS_PLACE : False
NPNP_SUCCESS_REWARD: 10.0
NPNP_SUCCESS_THRESH: 0.15 #0.3 #0.05
NPNP_FAILURE_PENALTY: 10.0
STATE_SENSORS:
  ROBOT_START_RELATIVE:
    TYPE: "RobotStartSensorConfig"
    polar: False
    obs_key: "robot_start_relative"
    shape: 3
  ROBOT_TARGET_RELATIVE:
    TYPE: "RobotTargetSensorConfig"
    polar: False
    obs_key: "robot_target_relative"
    shape: 3
  ROBOT_GOAL_RELATIVE:
    TYPE: "RobotGoalSensorConfig"
    polar: False
    obs_key: "robot_goal_relative"
    shape: 3
  EE_GOAL_RELATIVE:
    TYPE: "EEGoalSensorConfig"
    polar: False
    obs_key: "ee_goal_relative"
    shape: 3
  EE_START_RELATIVE:
    TYPE: "EEStartSensorConfig"
    polar: False
    obs_key: "ee_start_relative"
    shape: 3
  EE_TARGET_RELATIVE:
    TYPE: "EETargetSensorConfig"
    polar: False
    obs_key: "ee_target_relative"
    shape: 3
  ROBOT_EE_RELATIVE:
    TYPE: "RobotEESensorConfig"
    polar: False
    obs_key: "robot_ee_relative"
    shape: 3
  JOINT_SENSOR:
    TYPE: "JointSensorConfig"
    obs_key: "joint_pos"
    shape: 7
  STEP_COUNT_SENSOR:
    TYPE: "StepCountSensorConfig"
    obs_key: "step_count"
    shape: 3
  IS_HOLDING_SENSOR:
    TYPE: "HoldingSensorConfig"
    obs_key: "is_holding"
    shape: 1
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR", "ROBOT_START_RELATIVE", "ROBOT_TARGET_RELATIVE", "EE_START_RELATIVE", "EE_TARGET_RELATIVE", "ROBOT_EE_RELATIVE", "ROBOT_GOAL_RELATIVE", "EE_GOAL_RELATIVE", "IS_HOLDING_SENSOR", "JOINT_SENSOR", "STEP_COUNT_SENSOR"]
SIMULATOR:
  AGENTS: ['AGENT_0']
  HEAD_RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  HEAD_DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    NORMALIZE_DEPTH: true

RL:
  PPO:
    ppo_epoch: 1
    num_mini_batch: 2
    num_steps: 64
    entropy_coef: 0.0005
    lr: 3.5e-4
    use_normalized_advantage: True
    use_linear_lr_decay: True
    max_grad_norm: 2.0
  POLICY:
    name: "PointNavResNetPolicy"
    action_distribution_type: "gaussian"
  DDPPO:
    backbone: "resnet18"
FORCE_BLIND_POLICY: False
