# Copyright (c) Meta Platforms, Inc. All Rights Reserved

TENSORBOARD_DIR: "../data/tb/gala_kinematic_ddppo"
WRITER_TYPE: "tb"
CHECKPOINT_FOLDER: "../data/ckpt/gala_kinematic_ddppo"
EVAL_CKPT_PATH_DIR: "../data/ckpt/gala_kinematic_ddppo"
VIDEO_DIR: "../videos"
VIDEO_OPTION: ["disk"]
PROCEDURAL_GENERATION: True
NUM_ENVIRONMENTS: 64
DEBUG_SIM: True

NUM_UPDATES: 101
TOTAL_NUM_STEPS: -1.0
RL:
  POLICY:
    name: "PointNavBaselinePolicy"
