BASE_TASK_CONFIG_PATH: configs/tasks/rearrange/pick.yaml

SENSE_PLAN_ACT:
  VERBOSE: True
  RUN_FREQ: 2
  KINEMATIC_CTRL: True
  N_GRASPS: 100
  MP_OBJ: True
  MP_MARGIN: null
  MP_RENDER: True
  TIMEOUT: 3
  EXEC_EE_THRESH: 0.1
  # "Priv" or "Reg"
  MP_SIM_TYPE: "Priv"
  VIDEO_DIR: 'data/vids'
  DEBUG_DIR: "data/mp_test"
  COUNT_OBJ_COLLISIONS: True
  GRASP_GEN_IS_VERBOSE: True
  IK_DIST_THRESH: 0.1

EVAL:
  SPLIT: "eval"

TASK_CONFIG:
  SUCCESS_REWARD: 2000.0
  END_ON_SUCCESS: False

RL:
    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    EASY_INIT: False
VIDEO_DIR: "data/vids/"
VIDEO_OPTIONS: ["disk"]

COUNT_OBJ_COLLISIONS: True
COUNT_ROBOT_OBJ_COLLS: False
