# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents:
    - depth_head_agent
  - /habitat/task/rearrange: open_fridge
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    auto_name: OpenFridge
    obs_keys:
      - robot_head_depth
      - joint
      - ee_pos
      - is_holding
      - relative_resting_position
  environment:
    max_episode_steps: 200
  simulator:
    type: RearrangeSim-v0
    seed: 100
    additional_object_paths:
      - data/objects/ycb/configs/
    debug_render_goal: False
    agents:
      depth_head_agent:
        radius: 0.3
        sim_sensors:
          head_depth_sensor:
            height: 256
            width: 256
    hold_thresh: 0.2
    grasp_impulse: 10000.0
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
    needs_markers: False
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/in_fridge_1k_100.json.gz
