# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: depth_head_agent
  - /habitat/task/rearrange: place
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    auto_name: Place
    obs_keys:
      - robot_head_depth
      - obj_goal_sensor
      - joint
      - is_holding
      - relative_resting_position
  environment:
    max_episode_steps: 300
  simulator:
    type: RearrangeSim-v0
    additional_object_paths:
    - data/objects/ycb/configs/
    needs_markers: False
    concur_render: True
    auto_sleep: True
    agents:
      main_agent:
        sim_sensors:
          head_depth_sensor:
            width: 256
            height: 256
        radius: 0.3
        robot_urdf: ./data/robots/hab_fetch/robots/hab_suction_v2.urdf
        robot_type: FetchSuctionRobot
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz
