# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_head_rgbd_arm_agent
  - /habitat/task/rearrange: play
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  environment:
    max_episode_steps: 0
  simulator:
    type: RearrangeSim-v0
    seed: 100
    additional_object_paths:
      - "data/objects/ycb/configs/"
      - "data/object_datasets/amazon_berkeley/configs/"
      - "data/object_datasets/google_object_dataset/configs/"
    agents:
      main_agent:
        radius: 0.3
        robot_urdf: "data/robots/hab_spot_arm/urdf/hab_spot_arm.urdf"
        robot_type: "SpotRobot"
        sim_sensors:
          head_rgb_sensor:
            height: 128
            width: 128
          head_depth_sensor:
            height: 128
            width: 128
          arm_depth_sensor:
            height: 128
            width: 128
          arm_rgb_sensor:
            height: 128
            width: 128
    habitat_sim_v0:
      enable_physics: True
  dataset:
    data_path: "data/cat_split_1_test_scene_40k_old.json.gz"
    type: ObjectRearrangeDataset-v0
