# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /agent@habitat.simulator.agents.agent_0: agent_base
  - /habitat/simulator/sim_sensors:
    - head_depth_sensor
  - /habitat/task/rearrange: prepare_groceries
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    auto_name: PrepareGroceries
    obs_keys:
      - robot_head_depth
      - relative_resting_position
      - obj_start_sensor
      - obj_goal_sensor
      - obj_start_gps_compass
      - obj_goal_gps_compass
      - joint
      - is_holding
  environment:
    max_episode_steps: 4000
  simulator:
    type: RearrangeSim-v0
    seed: 100
    additional_object_paths:
      - "data/objects/ycb/configs/"
    concur_render: True
    auto_sleep: True
    agents:
      agent_0:
        radius: 0.3
        sim_sensors:
          head_depth_sensor:
            width: 128
            height: 128
    ctrl_freq: 120.0
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/prepare_groceries_10k_1k.json.gz
