# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/simulator/agents@habitat.simulator.agents.agent_0: agent_base
  - /habitat/simulator/sim_sensors@habitat.simulator.agents.agent_0.sim_sensors.head_depth_sensor: head_depth_sensor
  - /habitat/task/rearrange: reach_state
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    auto_name: ReachState
    obs_keys:
      - joint
      - relative_resting_position
    action_keys:
      - arm_action
  environment:
    max_episode_steps: 20
  simulator:
    type: RearrangeSim-v0
    seed: 100
    concur_render: True
    auto_sleep: True
    agents:
      agent_0:
        radius: 0.3
        sim_sensors:
          head_depth_sensor:
            height: 32
            width: 32
        is_set_start_state: True
        start_position: [0.0, 0.0, 2.0]
        start_rotation: [0.0, 0.0, 0.0, 1.0]
        ik_arm_urdf: ""
    # Agent setup
    ac_freq_ratio: 8

    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/empty_1k_100.json.gz
