# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /agent@habitat.simulator.agent_0: agent_base
  - /habitat/simulator/sim_sensors:
    - head_depth_sensor
  - /habitat/task/rearrange: rearrange_easy
  - /habitat/dataset/rearrangement: replica_cad
  - _self_

habitat:
  gym:
    auto_name: RearrangeEasy
    obs_keys:
      - robot_head_depth
      - relative_resting_position
      - obj_start_sensor
      - obj_goal_sensor
      - obj_start_gps_compass
      - obj_goal_gps_compass
      - joint
      - is_holding
  environment:
    max_episode_steps: 1500
  simulator:
    type: RearrangeSim-v0
    seed: 100
    additional_object_paths:
      - "data/objects/ycb/configs/"
    grasp_impulse: 10000.0
    hold_thresh: 0.2
    agent_0:
      height: 1.5
      radius: 0.3
      sim_sensors:
        head_depth_sensor:
          height: 256
          width: 256
      robot_urdf: ./data/robots/hab_fetch/robots/hab_suction.urdf
      robot_type: FetchSuctionRobot
    habitat_sim_v0:
      allow_sliding: False
      enable_physics: True
  dataset:
    data_path: data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz
