# @package _global_

defaults:
  - /objectnav: ddppo_objectnav_hm3d
  - override /benchmark/nav/objectnav: objectnav_v2_hm3d_stretch
  - _self_

habitat_baselines:
  rl:
    policy:
      action_distribution_type: gaussian
