# @package _global_

defaults:
  - /objectnav: ddppo_objectnav
  - /habitat_baselines/rl/policy/obs_transforms:
    - center_cropper_base
    - resize_shortest_edge_base
  - override /benchmark/nav/objectnav: objectnav_v2_hm3d_stretch
  - _self_

habitat_baselines:
  rl:
    policy:
      action_distribution_type: gaussian
