language: python
python:
  - "3.6"
install:
  - pip install pytest black isort
  - pip install .
script:
  - isort --recursive --check --trailing-comma --multi-line 3 --use-parentheses habitat test
  - black --check habitat test --line-length 79
  - pytest test/test_install.py

