# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: imagenav
  - /habitat/simulator/sim_sensors:
    - depth_sensor
    - rgb_sensor
  - _self_

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    agents:
      agent_0:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
          depth_sensor:
            width: 256
            height: 256
