# @package _global_

defaults:
  - base_rearrange_humanoid_spot
  # fetch specific defaults overrides:
  # (placeholder for future overrides)

# fetch specific config overrides:
# (placeholder for future overrides)
