name: "HierarchicalPolicy"
obs_transforms:
  add_virtual_keys:
    virtual_keys:
      "goal_to_agent_gps_compass": 2
hierarchical_policy:
  high_level_policy:
    name: "FixedHighLevelPolicy"
    add_arm_rest: True
  defined_skills:
    open_cab:
      skill_name: "ArtObjSkillPolicy"
      name: "PointNavResNetPolicy"
      load_ckpt_file: "data/models/open_cab.pth"
      max_skill_steps: 200

    open_fridge:
      skill_name: "ArtObjSkillPolicy"
      load_ckpt_file: "data/models/open_fridge.pth"
      max_skill_steps: 200

    close_cab:
      skill_name: "ArtObjSkillPolicy"
      obs_skill_inputs: ["obj_start_sensor"]
      load_ckpt_file: "data/models/close_cab.pth"
      max_skill_steps: 200

    close_fridge:
      skill_name: "ArtObjSkillPolicy"
      obs_skill_inputs: ["obj_start_sensor"]
      load_ckpt_file: "data/models/close_fridge.pth"
      max_skill_steps: 200

    pick:
      skill_name: "PickSkillPolicy"
      name: "PointNavResNetPolicy"
      action_distribution_type: "gaussian"
      at_resting_threshold: 0.15
      obs_skill_inputs: ["obj_start_sensor"]
      load_ckpt_file: "data/models/pick.pth"
      max_skill_steps: 200

    place:
      skill_name: "PlaceSkillPolicy"
      name: "PointNavResNetPolicy"
      action_distribution_type: "gaussian"
      at_resting_threshold: 0.15
      obs_skill_inputs: ["obj_goal_sensor"]
      load_ckpt_file: "data/models/place.pth"
      max_skill_steps: 200

    wait_skill:
      skill_name: "WaitSkillPolicy"
      max_skill_steps: -1
      force_end_on_timeout: False

    gt_nav:
      skill_name: "OracleNavPolicy"
      obs_skill_inputs: ["obj_start_sensor", "abs_obj_start_sensor", "obj_goal_sensor", "abs_obj_goal_sensor"]
      max_skill_steps: 300

    reset_arm_skill:
      skill_name: "ResetArmSkill"
      max_skill_steps: 50
      reset_joint_state: [-4.5003259e-01, -1.0799699e00, 9.9526465e-02, 9.3869519e-01, -7.8854430e-04, 1.5702540e00, 4.6168058e-03]
      force_end_on_timeout: False

  use_skills:
    # Uncomment if you are also using these skills
    # open_cab: "open_cab"
    # open_fridge: "open_fridge"
    # close_cab: "open_cab"
    # close_fridge: "open_fridge"
    pick: "pick"
    place: "place"
    nav: "gt_nav"
    nav_to_receptacle: "gt_nav"
    wait: "wait_skill"
    reset_arm: "reset_arm_skill"