# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: pointnav_franka
  - /habitat/simulator/sim_sensors:
    - rgb_sensor
  - /habitat/dataset/pointnav: habitat_test
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agent_0:
      robot_urdf: ./data/robots/franka_panda/panda_arm.urdf
      robot_type: "FrankaRobot"
      sim_sensors:
        rgb_sensor:
          width: 256
          height: 256
