---
dataset_path: "data/test_scene_dataset/floorplanner.scene_dataset_config.json"
additional_object_paths:
  - "data/objects/ycb/configs/"
scene_sets:
  -
    name: "any"
    included_substrings:
      - "102815859"
    excluded_substrings: []

object_sets:
  -
    name: "hab2"
    included_substrings:
      - "002_master_chef_can"
      - "003_cracker_box"
      - "004_sugar_box"
      - "005_tomato_soup_can"
      - "007_tuna_fish_can"
      - "008_pudding_box"
      - "009_gelatin_box"
      - "010_potted_meat_can"
      - "024_bowl"
    excluded_substrings: []
receptacle_sets:
  -
    name: "hab2"
    included_object_substrings:
      - ""
    excluded_object_substrings: []
    included_receptacle_substrings:
      - "receptacle_hall_shelf_lower"
      - "receptacle_hall_shelf_middle"
      - "receptacle_kitchen_counter_corner"
      - "receptacle_kitchen_counter_left"
      - "receptacle_kitchen_counter_middle"
      - "receptacle_kitchen_counter_right"
      - "receptacle_kitchen_island"
      - "receptacle_living_left_shelf_lower_left"
      - "receptacle_living_left_shelf_lower_middle_right"
      - "receptacle_living_left_shelf_lower_midle_left"
      - "receptacle_living_left_shelf_lower_right"
      - "receptacle_living_mantle"
      - "receptacle_living_right_shelf_lower_left"
      - "receptacle_living_right_shelf_lower_middle_right"
      - "receptacle_living_right_shelf_lower_midle_left"
      - "receptacle_living_right_shelf_lower_right"
      - "receptacle_living_table"
      - "receptacle_office_desk"
    excluded_receptacle_substrings: []

scene_sampler:
  type: "subset"
  params:
  #   scene_sets: ["scene_train_split", "scene_val_split"]
    scene_sets: ["any"]

object_samplers:
  -
    name: "hab2"
    type: "uniform"
    params:
      object_sets: ["hab2"]
      receptacle_sets: ["hab2"]
      num_samples: [1, 25]
      orientation_sampling: "up"
      nav_to_min_distance: 1.5

object_target_samplers:
  -
    name: "hab2"
    type: "uniform"
    params:
      object_samplers: ["hab2"]
      receptacle_sets: ["hab2"]
      num_samples: [1, 1]
      orientation_sampling: "up"
      nav_to_min_distance: 1.5
