BASE_TASK_CONFIG_PATH: "configs/tasks/eqa_mp3d.yaml"
TRAINER_NAME: "edfe"

ENV_NAME: "EDFEILEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0

DATASET_PATH: "data/datasets/eqa/edfe_dataset/{split}/{type}"

EVAL_CKPT_PATH_DIR: "data/eqa/edfe/checkpoints"

CHECKPOINT_FOLDER: "data/eqa/edfe/checkpoints"
TENSORBOARD_DIR: "data/eqa/edfe/tb"
RESULTS_DIR: "data/eqa/edfe/results/{split}/{type}" 
OUTPUT_LOG_DIR: data/eqa/edfe/logs

LOG_METRICS: True
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 1
EVAL_SAVE_RESULTS: True
EVAL_SAVE_RESULTS_INTERVAL: 20

IL:
  EDFE:
    # edfe params
    max_epochs: 20
    batch_size: 40
    lr: 1e-3
