# @package _global_

defaults:
  - pop_play_kinematic_oracle
  - /habitat_baselines/rl/auxiliary_losses: bdp_discrim
  - override /habitat_baselines/rl/agent: bdp
  - _self_

habitat_baselines:
  rl:
    auxiliary_losses:
      bdp_discrim:
        loss_scale: 0.1
        behavior_latent_dim: 16
    agent:
      num_pool_agents_per_type: [1, 1]
      behavior_latent_dim: 16
    policy:
      agent_1:
        # This is the behav policy.
        hierarchical_policy:
          high_level_policy:
            policy_input_keys:
              - "head_depth"
              - "behav_latent"
                # auxiliary_losses:
                #   bdp_discrim: 
                #     loss_scale: 0.1

