# @package _global_

defaults:
  - pop_play_kinematic_oracle
  - override /habitat_baselines/rl/agent: bdp
  - _self_

habitat_baselines:
  rl:
    agent:
      num_pool_agents_per_type: [1, 1]
      behavior_latent_dim: 16
