# @package _global_

defaults:
  - pop_play_kinematic_oracle_humanoid_spot_fp
  - /habitat_baselines/rl/auxiliary_losses: bdp_discrim
  - override /habitat_baselines/rl/agent: bdp
  - _self_

hydra:
  job:
    name: 'bdp_humanoid_spot'

habitat_baselines:
  rl:
    auxiliary_losses:
      bdp_discrim:
        loss_scale: 0.1
        behavior_latent_dim: 16
    agent:
      # BDP uses a behavior latent to create a population, instead of multiple independent policies.
      num_pool_agents_per_type: [1, 1]
      behavior_latent_dim: 16
      discrim_reward_weight: 0.001
    policy:
      agent_1:
        # This is the behav policy.
        hierarchical_policy:
          high_level_policy:
            policy_input_keys:
              - "head_depth"
              - "is_holding"
              - "obj_start_gps_compass"
              - "obj_goal_gps_compass"
              - "other_agent_gps"
              - "behav_latent"
