# @package _global_

defaults:
  - pop_play_kinematic_oracle_humanoid_spot_fp_learned_skill
  # - override /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_0: hl_fixed # hab3_planner
  - override /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_1: hab3_planner
  - _self_

hydra:
  job:
    name: 'planner_humanoid_spot_fp'

habitat_baselines:
  eval:
    should_load_ckpt: True
    video_option: []

  rl:
    agent:
      num_pool_agents_per_type: [1, 1]
      agent_sample_interval: 20
      force_partner_sample_idx: -1
    policy:
      agent_1:
        hierarchical_policy:
          high_level_policy:
            plan_idx: -2 # -2 means use different subsets for different envs
