# @package _global_

defaults:
  - pop_play_kinematic_oracle_humanoid_spot_fp
  - /habitat/task/lab_sensors:
    # For the oracle navigation
    - all_predicates

  - override /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_0: hab3_hl_neural_ma
  - override /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_1: hab3_planner
  - _self_

hydra:
  job:
    name: 'pop_play_humanoid_spot_fp'


habitat:
  gym:
    obs_keys:
      - agent_0_articulated_agent_arm_depth
      - agent_0_relative_resting_position
      - agent_0_obj_start_sensor
      - agent_0_obj_goal_sensor
      - agent_0_obj_start_gps_compass
      - agent_0_obj_goal_gps_compass
      - agent_0_is_holding
      - agent_0_ee_pos
      - agent_0_localization_sensor
      - agent_0_has_finished_oracle_nav
      - agent_0_other_agent_gps
      - agent_0_should_replan
      - agent_1_head_depth
      - agent_1_relative_resting_position
      - agent_1_obj_start_sensor
      - agent_1_obj_goal_sensor
      - agent_1_obj_start_gps_compass
      - agent_1_obj_goal_gps_compass
      - agent_1_is_holding
      - agent_1_ee_pos
      - agent_1_localization_sensor
      - agent_1_has_finished_oracle_nav
      - agent_1_other_agent_gps
      - agent_1_should_replan
      - all_predicates
habitat_baselines:
  eval:
    should_load_ckpt: False
    video_option: ["disk"]

  rl:
    agent:
      num_pool_agents_per_type: [1, 1]
      agent_sample_interval: 20
      force_partner_sample_idx: -1
    policy:
      agent_1:
        hierarchical_policy:
          high_level_policy:
            plan_idx: -2 # -2 means use different subsets for different envs
