# @package habitat.simulator.agents.fetch_suction
defaults:
  - agent_base
  - _self_

radius: 0.3
articulated_agent_urdf: ./data/robots/hab_fetch/robots/hab_suction.urdf
articulated_agent_type: FetchSuctionRobot
