# @package habitat.simulator.agents.human
radius: 0.3
articulated_agent_urdf: 'data/humanoids/humanoid_data/armatures/human_armature.urdf'
articulated_agent_type: 'KinematicHumanoid'
sim_sensors:
  head_rgb_sensor:
    height: 128
    width: 128
  head_depth_sensor:
    height: 128
    width: 128
  arm_depth_sensor:
    height: 128
    width: 128
  arm_rgb_sensor:
    height: 128
    width: 128
