# @package _global_

# Extends the `rl_hierarchical` config to use an oracle navigation action.
# Several things change to support the oracle navigation:
# - Adding the oracle navigation action
# - Add sliding.
# - Use the oracle navigation skill.

defaults:
  - rl_hierarchical
  - /habitat/task/actions:
    - pddl_apply_action
    - oracle_nav_action
    - human_nav_action
    - human_pick_action
    - human_place_action
    - humanjoint_action
  - override /habitat_baselines/rl/policy/hierarchical_policy/defined_skills: oracle_skills_human
  - override /benchmark/rearrange: rearrange_easy_human
  - _self_

habitat:
  gym:
    obs_keys:
      - robot_head_depth
      - relative_resting_position
      - obj_start_sensor
      - obj_goal_sensor
      - obj_start_gps_compass
      - obj_goal_gps_compass
      - human_joint
      - is_holding
      - ee_pos
      - localization_sensor
  simulator:
    habitat_sim_v0:
      allow_sliding: True
    agents:
      main_agent:
        agent_urdf: 'data/human_sim_data/amass_male.urdf'
        ik_arm_urdf: 'data/human_sim_data/amass_male.urdf'
        agent_type: 'AmassHuman'
        draw_fps_human: 15
        amass_path: 'data/human_sim_data/amass_smpl_h/'
        body_model_path: 'data/human_sim_data/smplh/male/model.npz'
        grab_path: 'data/human_sim_data/left_hand_smplh_hand.npz'

habitat_baselines:
  num_environments: 1 
  rl:
    policy:
      hierarchical_policy:
        # Override to use the oracle navigation skill.
        defined_skills:
          nav_to_obj:
            skill_name: "OracleNavHumanPolicy"
            obs_skill_inputs: ["obj_start_sensor", "abs_obj_start_sensor", "obj_goal_sensor", "abs_obj_goal_sensor"]
            max_skill_steps: 300
            pddl_action_names: ["nav", "nav_to_receptacle"]
