# @package _global_

defaults:
  - /benchmark/rearrange: rearrange_easy
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /habitat_baselines/rl/policy: hierarchical_learned_nav
  - /habitat_baselines/rl/policy/obs_transforms:
    - add_virtual_keys_base
  - _self_


habitat_baselines:
  verbose: False
  trainer_name: "ddppo"
  torch_gpu_id: 0
  tensorboard_dir: "tb"
  video_dir: "video_dir"
  video_fps: 30
  video_render_views:
    - "third_rgb_sensor"
  test_episode_count: -1
  eval_ckpt_path_dir: ""
  num_environments: 1
  writer_type: 'tb'
  checkpoint_folder: "data/new_checkpoints"
  num_updates: -1
  total_num_steps: 1.0e8
  log_interval: 10
  num_checkpoints: 20
  force_torch_single_threaded: True
  eval_keys_to_include_in_name: ['reward', 'force', 'composite_success']
  load_resume_state_config: False
  eval:
    use_ckpt_config: False
    should_load_ckpt: False
    video_option: ["disk"]

  rl:
    ddppo:
      pretrained: False
      pretrained_encoder: False
      train_encoder: True
      reset_critic: False
