habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agent_0:
      sensors: ['rgb_sensor']
    habitat_sim_v0:
      gpu_device_id: 0
    rgb_sensor:
      width: 256
      height: 256
    depth_sensor:
      width: 256
      height: 256
  task:
    type: Nav-v0

    sensors: ['imagegoal_sensor']
    goal_sensor_uuid: imagegoal

    measurements: ['distance_to_goal', 'success', 'spl']
    success:
      success_distance: 0.2
