FIX_BASE_TO_OBJ: None
FORCE_BASED: True
MAX_ACCUM_FORCE: 5000.0
MAX_COLLISIONS: 2000.0
COUNT_OBJ_COLLISIONS: True
COUNT_ROBO_OBJ_COLLS: False

ENVIRONMENT:
    MAX_EPISODE_STEPS: 200
DATASET:
    TYPE: OrpDataset-v0
    SPLIT: train
    DATA_PATH: data/episode_data/{split}_counter_L_analysis_5000_500.json.gz
    SCENES_DIR: "data/scene_datasets/"
TASK:
    TYPE: OrpTask-v0

    TARGET_START_SENSOR:
        TYPE: "TargetStartSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    GOAL_SENSOR:
        TYPE: "GoalSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    ABS_TARGET_START_SENSOR:
        TYPE: "AbsTargetStartSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    ABS_GOAL_SENSOR:
        TYPE: "AbsGoalSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    JOINT_SENSOR:
        TYPE: "JointSensor"
    EE_SENSOR:
        TYPE: "EeSensor"
    IS_HOLDING_SENSOR:
        TYPE: "IsHoldingSensor"
    LOCAL_SENSOR:
        TYPE: "LocalizationSensor"
    SENSORS: ["TARGET_START_SENSOR", "GOAL_SENSOR", "JOINT_SENSOR", "IS_HOLDING_SENSOR", "EE_SENSOR", "LOCAL_SENSOR"]
    OBJECT_TO_GOAL_DISTANCE:
        TYPE: "ObjectToGoalDistance"
    END_EFFECTOR_TO_OBJECT_DISTANCE:
        TYPE: "EndEffectorToObjectDistance"
    MEASUREMENTS:
        - "OBJECT_TO_GOAL_DISTANCE"
        - "END_EFFECTOR_TO_OBJECT_DISTANCE"

SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    AC_FREQ_RATIO: 4
    AGENTS: ['AGENT_0']
    AGENT_0:
        ANGULAR_ACCELERATION: 12.56
        ANGULAR_FRICTION: 1.0
        COEFFICIENT_OF_RESTITUTION: 0.0
        HEIGHT: 1.5
        IS_SET_START_STATE: False
        LINEAR_ACCELERATION: 20.0
        LINEAR_FRICTION: 0.5
        MASS: 32.0
        RADIUS: 0.1
        SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'ARM_RGB_SENSOR', 'ARM_DEPTH_SENSOR']
        START_POSITION: [0, 0, 0]
        START_ROTATION: [0, 0, 0, 1]
    ARM_DEPTH_SENSOR:
        HEIGHT: 128
        HFOV: 90
        MAX_DEPTH: 10.0
        MIN_DEPTH: 0.0
        NORMALIZE_DEPTH: True
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 0, 0]
        TYPE: ArmDepthSensor
        WIDTH: 128
    ARM_REST: [0.6, 0.0, 0.9]
    ARM_RGB_SENSOR:
        HEIGHT: 128
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 0, 0]
        TYPE: ArmRgbSensor
        WIDTH: 128
    CTRL_FREQ: 120.0
    DEFAULT_AGENT_ID: 0
    DEPTH_SENSOR:
        HEIGHT: 128
        HFOV: 90
        MAX_DEPTH: 10.0
        MIN_DEPTH: 0.0
        NORMALIZE_DEPTH: True
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 0, 0]
        TYPE: HabitatSimDepthSensor
        WIDTH: 128
    FORWARD_STEP_SIZE: 0.25
    HABITAT_SIM_V0:
        ALLOW_SLIDING: True
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    HIGH_RES_DIM: 512
    LAG_OBSERVATIONS: 2
    POV: 1st
    RGB_SENSOR:
        HEIGHT: 128
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 0, 0]
        TYPE: HabitatSimRGBSensor
        WIDTH: 128
    ROBOT_URDF: ./orp/robots/opt_fetch/robots/fetch_no_base.urdf
    SCENE: data/scene_datasets/habitat-test-scenes/van-gogh-room.glb
    SEED: 100
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 1.25, 0]
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: OrpSim-v0
