RL:
    REWARD_MEASURE: "object_to_goal_distance"
    SUCCESS_MEASURE: "object_to_goal_distance"
    SUCCESS_REWARD: 2000.0
    SLACK_REWARD: -0.01

    DIST_REWARD: 20.0
    SUCC_REWARD: 10.0
    PICK_REWARD: 20.0
    CONSTRAINT_VIOLATE_PEN: 10.0
    DROP_PEN: 5.0
    WRONG_PICK_PEN: 5.0
    COLL_PEN: 1.0
    ROBO_OBJ_COLL_PEN: 0.0

    FORCE_PEN: 0.001
    MAX_FORCE_PEN: 1.0
    FORCE_END_PEN: 10.0

    USE_DIFF: True

    SUCC_THRESH: 0.15
    HOLD_THRESH: 0.09
    # In radians
    BASE_ANGLE_NOISE: 0.15
    BASE_NOISE: 0.05
    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    EASY_INIT: False

MAX_COLLISIONS: 2000.0
FORCE_BASED: True
COUNT_OBJ_COLLISIONS: True
COUNT_ROBO_OBJ_COLLS: False
# A value of -1 means the episode will never terminate due to a force
# violation.
MAX_ACCUM_FORCE: 5000.0
TASK_CONFIG:
    ENVIRONMENT:
        MAX_EPISODE_STEPS: 200
    TASK:
        REARRANGE_TASK:
            TARGET_START_SENSOR:
                TYPE: "TargetStartSensor"
                GOAL_FORMAT: "CARTESIAN"
                DIMENSIONALITY: 3
            GOAL_SENSOR:
                TYPE: "GoalSensor"
                GOAL_FORMAT: "CARTESIAN"
                DIMENSIONALITY: 3
            ABS_TARGET_START_SENSOR:
                TYPE: "AbsTargetStartSensor"
                GOAL_FORMAT: "CARTESIAN"
                DIMENSIONALITY: 3
            ABS_GOAL_SENSOR:
                TYPE: "AbsGoalSensor"
                GOAL_FORMAT: "CARTESIAN"
                DIMENSIONALITY: 3
            JOINT_SENSOR:
                TYPE: "JointSensor"
            EE_SENSOR:
                TYPE: "EeSensor"
            IS_HOLDING_SENSOR:
                TYPE: "IsHoldingSensor"
            LOCAL_SENSOR:
                TYPE: "LocalizationSensor"
            SENSORS: ["TARGET_START_SENSOR", "GOAL_SENSOR", "JOINT_SENSOR", "IS_HOLDING_SENSOR", "EE_SENSOR", "LOCAL_SENSOR"]
            OBJECT_TO_GOAL_DISTANCE:
                TYPE: "ObjectToGoalDistance"
            END_EFFECTOR_TO_OBJECT_DISTANCE:
                TYPE: "EndEffectorToObjectDistance"
            MEASUREMENTS:
                - "OBJECT_TO_GOAL_DISTANCE"
                - "END_EFFECTOR_TO_OBJECT_DISTANCE"
ENV_NAME: "RearrangPickRLEnv"
