ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 15
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 512
    HEIGHT: 512
    HFOV: 45
    TYPE: HabitatSimRGBSensor
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: VLN-v0
  SUCCESS_DISTANCE: 2.0
  SENSORS: ['INSTRUCTION_SENSOR']
  MEASUREMENTS: ['SPL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 2.0
DATASET:
  TYPE: R2RVLN-v1
  SPLIT: train
  DATA_PATH: data/datasets/R2R/hb_R2R_{split}.json
  SCENES_DIR: data/scene_datasets/mp3d/
