# @package habitat.task

defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - rearrange_stop
    - base_velocity
    - arm_action
    - extend_arm
    - face_arm
    - reset_joints
  - /habitat/task/measurements:
    - object_to_goal_distance
    - robot_force
    - force_terminate
    - robot_colls
    - does_want_terminate
    - num_steps
    - obj_anywhere_on_goal
    - end_effector_to_rest_distance
    - did_pick_object
    - pick_success
    - place_success
    - dist_to_pick_goal
    - rot_dist_to_pick_goal
    - nav_to_pick_succ
    - nav_orient_to_pick_succ
    - dist_to_place_goal
    - rot_dist_to_place_goal
    - nav_to_place_succ
    - nav_orient_to_place_succ
    - pick_nav_to_place_succ
    - pick_nav_orient_to_place_succ
  - /habitat/task/lab_sensors:
    - joint_sensor
    - joint_velocity_sensor
    - object_category_sensor
    - start_receptacle_sensor
    - goal_receptacle_sensor
    - object_segmentation_sensor
    - object_embedding_sensor
    - start_recep_segmentation_sensor
    - goal_recep_segmentation_sensor
    - robot_start_gps_sensor
    - robot_start_compass_sensor
    - camera_pose_sensor
    - end_effector_sensor
    - relative_resting_pos_sensor
    - is_holding_sensor
    - cat_nav_goal_segmentation_sensor
    - receptacle_segmentation_sensor
  - _self_

type: CatNavToObjTask-v0
reward_measure: place_success
success_measure: place_success
success_reward: 10.0
slack_reward: -0.005
end_on_success: True
constraint_violation_ends_episode: False
constraint_violation_drops_object: True
object_in_hand_sample_prob: 0.0
actions:
  arm_action:
    type: "ArmAction"
    arm_controller: "ArmRelPosReducedActionStretch"
    grip_controller: "GazeGraspAction"
    arm_joint_mask: [1,0,0,0,1,1,1,1,1,1]
    arm_joint_dimensionality: 7
    grasp_thresh_dist: 0.15
    disable_grip: False
    delta_pos_limit: 1 # TODO: temporary
    ee_ctrl_lim: 0.015
    gaze_distance_range: [0.1, 3.0]
    center_cone_angle_threshold: 90.0
    center_cone_vector: [0.0, 1.0, 0.0]
    oracle_snap: True
  base_velocity:
    type: "BaseWaypointTeleportAction"
    navmesh_offset: [[0.0, 0.0]]
measurements:
  force_terminate:
    max_accum_force: -1.0
    max_instant_force: -1.0
  pick_success: 
    object_goal: True
    ee_resting_success_threshold: 100
  place_success:
    place_anywhere: True
    ee_resting_success_threshold: 100
  dist_to_pick_goal:
    use_shortest_path_cache: False # when caching, the same set of goals are used throughout
  dist_to_place_goal:
    use_shortest_path_cache: False # when caching, the same set of goals are used throughout
  nav_orient_to_pick_succ:
    must_call_stop: False
  nav_orient_to_place_succ:
    must_call_stop: False
lab_sensors:
  joint_sensor:
    dimensionality: 10
  joint_velocity_sensor:
    dimensionality: 10