# @package habitat.task

defaults:
  - /habitat/task: task_config_base
  - /habitat/task/actions:
    - arm_action
  - /habitat/task/measurements:
    - robot_force
    - force_terminate
    - robot_colls
    - end_effector_to_rest_distance
    - object_to_goal_distance
    - obj_at_goal
    - place_success
    - place_reward
    - num_steps
  - /habitat/task/lab_sensors:
    - target_start_sensor
    - goal_sensor
    - joint_sensor
    - joint_velocity_sensor
    - is_holding_sensor
    - end_effector_sensor
    - relative_resting_pos_sensor
    - object_sensor
  - _self_

type: RearrangePlaceTask-v0
constraint_violation_ends_episode: False
constraint_violation_drops_object: True
reward_measure: place_reward
success_measure: place_success
success_reward: 10.0
slack_reward: 0.0
end_on_success: True
actions:
  arm_action:
    grip_controller: SuctionGraspAction
measurements:
  force_terminate:
    max_accum_force: 5000.0
  place_reward:
    drop_pen: 0.0
