GYM:
    AUTO_NAME: "OpenCab"
    OBS_KEYS: ['robot_head_depth', "robot_head_semantic", "ee_pos", 'joint', 'is_holding', "relative_resting_position"]
ENVIRONMENT:
    MAX_EPISODE_STEPS: 1000
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/in_drawer_1k_100.json.gz
    SCENES_DIR: data/replica_cad/
EVAL:
    SPLIT: train # train or val
TASK:
    TYPE: RearrangeOpenDrawerTask-v0
    COUNT_OBJ_COLLISIONS: true
    COUNT_ROBOT_OBJ_COLLS: false
    DESIRED_RESTING_POSITION: [0.11, -0.38, 0.22]
    SETTLE_STEPS: 5
    BASE_ANGLE_NOISE: 0.05 #0.15
    SPAWN_REGION_SCALE: 0.2
    JOINT_MAX_IMPULSE: -1.0
    CONSTRAINT_VIOLATION_ENDS_EPISODE: true
    USE_MARKER_T: true
    SUCCESS_STATE: 0.45
    REWARD_MEASURE: art_obj_reward
    SUCCESS_MEASURE: art_obj_success
    SUCCESS_REWARD: 10.0
    SLACK_REWARD: 0.0
    END_ON_SUCCESS: true
    EASY_INIT: false
    JOINT_SENSOR:
        TYPE: JointSensor
        DIMENSIONALITY: 10
    JOINT_VELOCITY_SENSOR:
        TYPE: JointVelocitySensor
        DIMENSIONALITY: 10
    END_EFFECTOR_SENSOR:
        TYPE: EEPositionSensor
    IS_HOLDING_SENSOR:
        TYPE: IsHoldingSensor
    RELATIVE_RESTING_POS_SENSOR:
        TYPE: RelativeRestingPositionSensor
    SENSORS: ["JOINT_VELOCITY_SENSOR", "JOINT_SENSOR", "IS_HOLDING_SENSOR", "END_EFFECTOR_SENSOR", "RELATIVE_RESTING_POS_SENSOR"]
    ROBOT_FORCE:
        TYPE: RobotForce
        MIN_FORCE: 20.0
    FORCE_TERMINATE:
        TYPE: ForceTerminate
        MAX_ACCUM_FORCE: -1.0
    ROBOT_COLLS:
        TYPE: RobotCollisions
    ART_OBJ_STATE:
        TYPE: ArtObjState
    EE_DIST_TO_MARKER:
        TYPE: EndEffectorDistToMarker
    END_EFFECTOR_TO_REST_DISTANCE:
        TYPE: EndEffectorToRestDistance
    ART_OBJ_AT_DESIRED_STATE:
        TYPE: ArtObjAtDesiredState
        USE_ABSOLUTE_DISTANCE: false
        SUCCESS_DIST_THRESHOLD: 0.05
    ART_OBJ_SUCCESS:
        TYPE: ArtObjSuccess
        REST_DIST_THRESHOLD: 0.15
    ART_OBJ_REWARD:
        TYPE: ArtObjReward
        WRONG_GRASP_END: true
        WRONG_GRASP_PEN: 5.0
        GRASP_REWARD: 5.0
        ART_AT_DESIRED_STATE_REWARD: 5.0
        MARKER_DIST_REWARD: 1.0
        EE_DIST_REWARD: 10.0
        ART_DIST_REWARD: 10.0
        CONSTRAINT_VIOLATE_PEN: 1.0
        FORCE_PEN: 0.0
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0
    ARM_DEPTH_SENSOR:
      HEIGHT: 128
      WIDTH: 128
      MAX_DEPTH: 10.0
      MIN_DEPTH: 0.0
      NORMALIZE_DEPTH: True
    ARM_SEMANTIC_SENSOR:
      HEIGHT: 128
      WIDTH: 128
    NUM_STEPS:
        TYPE: NumStepsMeasure
    DID_VIOLATE_HOLD_CONSTRAINT:
        TYPE: DidViolateHoldConstraintMeasure
    MEASUREMENTS:
    - ROBOT_FORCE
    - FORCE_TERMINATE
    - ROBOT_COLLS
    - END_EFFECTOR_TO_REST_DISTANCE
    - EE_DIST_TO_MARKER
    - ART_OBJ_AT_DESIRED_STATE
    - ART_OBJ_STATE
    - ART_OBJ_SUCCESS
    - ART_OBJ_REWARD
    - NUM_STEPS
    - DID_VIOLATE_HOLD_CONSTRAINT
    ACTIONS:
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmRelPosKinematicReducedActionStretch" #  or ArmRelPosAction
            GRIP_CONTROLLER: "MagicGraspAction"
            ARM_JOINT_MASK: [1,0,0,0,1,1,1,1,1,1] # mask out the arm
            ARM_JOINT_DIMENSIONALITY: 10
            GRASP_THRESH_DIST: 0.15
            DISABLE_GRIP: False
            DELTA_POS_LIMIT: 0.0125
            EE_CTRL_LIM: 0.015
            RENDER_EE_TARGET: True
            PREVENT_PENETRATION: True
    POSSIBLE_ACTIONS:
        - ARM_ACTION
SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
        - data/objects/ycb/configs/
    DEBUG_RENDER: false
    DEBUG_RENDER_GOAL: false
    ACTION_SPACE_CONFIG: v0
    AGENTS:
        - AGENT_0
    AGENT_0:
        HEIGHT: 1.5
        RADIUS: 0.3
        SENSORS: [HEAD_RGB_SENSOR, HEAD_DEPTH_SENSOR, HEAD_SEMANTIC_SENSOR]
        ROBOT_URDF: /Users/jimmytyyang/Documents/hab_stretch/urdf/hab_stretch.urdf
        ROBOT_TYPE: StretchRobot
        IK_ARM_URDF:
    HEAD_RGB_SENSOR:
        WIDTH: 120
        HEIGHT: 212
        HFOV: 69
    HEAD_DEPTH_SENSOR:
        WIDTH: 120
        HEIGHT: 212
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: True
    HEAD_SEMANTIC_SENSOR:
        HEIGHT: 212
        WIDTH: 120
    CTRL_FREQ: 120.0
    AC_FREQ_RATIO: 4
    FORWARD_STEP_SIZE: 0.25
    HOLD_THRESH: 1.0 # There is a bug here as the robot open the drawer, it will be large#0.2
    GRASP_IMPULSE: 10000.0
    DEFAULT_AGENT_ID: 0
    HABITAT_SIM_V0:
        ALLOW_SLIDING: false
        ENABLE_PHYSICS: true
        GPU_DEVICE_ID: 0
        GPU_GPU: false
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    TYPE: RearrangeSim-v0
    COLLISION_DETECTION_METHOD: "ContactTestRevert"
    NEEDS_MARKERS: false
    KINEMATIC_MOD: True
