# @package _global_

defaults:
  - social_rearrange: pop_play
  - hitl_defaults
  - disable_spot_pick_and_move_backward
  - _self_

habitat:
  # various config args to ensure the episode never ends
  environment:
    max_episode_steps: 0
    iterator_options:
      # For the demo, we want to showcase the episodes in the specified order
      shuffle: False
  task:
    measurements:
      rearrange_cooperate_reward:
        end_on_collide: False
      pddl_success:
        must_call_stop: False
  dataset:
    data_path: examples/hitl/rearrange_v2/app_data/demo.json.gz

  gym:
    obs_keys:
      # - agent_0_articulated_agent_arm_depth
      # - agent_0_spot_head_stereo_depth_sensor
      # - agent_0_humanoid_detector_sensor
      - agent_1_head_depth
      - agent_1_relative_resting_position
      - agent_1_obj_start_sensor
      - agent_1_obj_goal_sensor
      - agent_1_obj_start_gps_compass
      - agent_1_obj_goal_gps_compass
      - agent_1_is_holding
      - agent_1_ee_pos
      - agent_1_localization_sensor
      - agent_1_has_finished_oracle_nav
      - agent_1_other_agent_gps


habitat_baselines:
  # todo: document these choices
  eval:
    should_load_ckpt: False
  rl:
    agent:
      num_pool_agents_per_type: [1,1]

habitat_hitl:
  window:
    title: "Rearrange"
    width: 1300
    height: 1000
  gui_controlled_agent:
    agent_index: 1
    ang_speed: 300
  hide_humanoid_in_gui: True
  camera:
    first_person_mode: True
